title: Typoblog
description: A website with a blog
header_text: Eat well with good typography
footer_text: Copyright 2020 Ellie Duncan
header_feature_image: ../uploads/books4screen.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
